# Generated by Django 4.1.3 on 2022-12-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
