# Generated by Django 4.1.3 on 2022-12-03 18:21

import django.core.validators
from django.db import migrations, models
import shopping_cart.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_shoppingcartuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3), shopping_cart.accounts.models.validate_alphabetical_letters]),
        ),
        migrations.AlterField(
            model_name='shoppingcartuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcartuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3), shopping_cart.accounts.models.validate_alphabetical_letters]),
        ),
    ]
