# Generated by Django 4.1.3 on 2022-12-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_products_user'),
        ('accounts', '0003_alter_shoppingcartuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartuser',
            name='cart_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.products'),
        ),
    ]
