# Generated by Django 4.1.3 on 2022-12-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_products_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
    ]
