# Generated by Django 4.1.3 on 2022-12-09 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0006_addproducttousercart'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveProductToUserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('product_in_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.addproducttousercart')),
            ],
        ),
    ]
